routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//Admin Namespace
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\ChangePasswordController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\WorkOrderAcController;
use App\Http\Controllers\Admin\WorkOrderPompaController;

//Controllers Namespace
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\PengumumanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//login
Route::get('/', 'AuthController@showFormLogin')->name('login');
Route::get('login', 'AuthController@showFormLogin')->name('login');
Route::post('login', 'AuthController@login');

//registration
Route::get('registrasi', 'RegisController@index')->name('regis');
Route::post('regis/form', 'RegisController@regisForm')->name('regisForm');
// Route::post('login', 'RegisController@login');

//Home
Route::get('/',[HomeController::class,'index']);
Route::get('/home',[AdminController::class,'index'])->name('index');
Route::get('/about',[HomeController::class,'about'])->name('about');
Route::get('/contact',[HomeController::class,'contact'])->name('contact');

//Artikel
// Route::get('/artikel',[ArtikelController::class,'index'])->name('artikel');
// Route::get('/artikel/search',[ArtikelController::class,'search'])->name('artikel.search');

// Route::get('/artikel/{artikel:slug}',[ArtikelController::class,'show'])->name('artikel.show');

//Pengumuman
Route::get('/pengumuman',[PengumumanController::class,'index'])->name('pengumuman');
Route::get('/pengumuman/{pengumuman:slug}',[PengumumanController::class,'show'])->name('pengumuman.show');

//WorkOrderPompa
// Route::get('/pompa',[WorkOrderPompaController::class,'index'])->name('pompa');
// Route::get('/pompa/search',[WorkOrderPompaController::class,'search'])->name('pompa.search');
// Route::get('/pompa/{pompa:slug}',[WorkOrderP\ompaController::class,'show'])->name('pompa.show');

Route::get('/pdf/{id}', 'Admin\WorkOrderAcController@pdf')->name('cetakPDF');
Route::get('/pompa/{id}', 'Admin\WorkOrderPompaController@pdf')->name('cetakPDFPompa');
Route::get('/alarm/{id}', 'Admin\WorkOrderFireAlarmController@pdf')->name('cetakPDFFireAlarm');

//Admin
Route::group(['namespace' => 'Admin','prefix' => 'admin','middleware' => ['auth']],function(){
	Route::name('admin.')->group(function(){

		Route::get('/',[AdminController::class,'index'])->name('index');
		Route::get('/profile',[ProfileController::class,'index'])->name('profile.index');
		Route::get('/change-password',[ChangePasswordController::class,'index'])->name('change-password.index');

		//Resource Controller
		Route::resource('users','UsersController');
		// Route::resource('pengumuman','PengumumanController');
		// Route::resource('agenda','AgendaController');
		Route::resource('wo_ac','WorkOrderAcController');
		// Route::resource('pompa','WorkOrderPompaController');
		// Route::resource('fire_alarm','WorkOrderFireAlarmController');
		Route::resource('perusahaan','PerusahaanController');
		Route::resource('department','DepartmentController');
		Route::resource('karyawan','KaryawanController');
		// Route::resource('alat','PeralatanController');
		// Route::resource('kategori-artikel','KategoriArtikelController');
	});
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

use App\Models\Artikel;
use App\Models\Pengumuman;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'username',
        // 'nip',
        'name',
        // 'birth_date',
        // 'phone_number',
        // 'gender',
        // 'address',
        // 'religion',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function artikel()
    {
        return $this->hasMany(Artikel::class);
    }

    public function pengumuman()
    {
        return $this->hasMany(Pengumuman::class);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\User;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $count_kode = User::count('nip');
        // $user       = "PGW" . date("y-") . (sprintf('%05d', $count_kode + 1));
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->request->add(['password' => bcrypt($request->password)]);
        User::create($request->all());
        return redirect()->route('admin.users.index')->with('success','Data berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit',compact('user'));   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->request->add(['password' => $request->password ? bcrypt($request->password) : $request->old_password]);
        $user->update($request->all());
        return redirect()->route('admin.users.index')->with('success','Data berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('admin.users.index')->with('success','Data berhasil dihapus');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.backend.app',[
	'title' => 'Tambah Users',
	'contentTitle' => 'Tambah Users',
])
@section('content')
<div class="row">
	<div class="col">
		<div class="card">
			<div class="card-header">
				<a href="{{ route('admin.users.index') }}" class="btn btn-success btn-sm">Kembali</a>
			</div>
			<div class="card-body">
				<form method="POST" action="{{ route('admin.users.store') }}">
					@csrf
					<div class="form-group">
						<label for="name">Full Name</label>
						<input required="" class="form-control" type="" name="name" id="name" placeholder="">
					</div>
					<div class="form-group">
						<label for="email">Email</label>
						<input required="" class="form-control" type="" name="email" id="email" placeholder="">
					</div>
					<div class="form-group">
						<label for="username">Username</label>
						<input required="" class="form-control" type="" name="username" id="username" placeholder="">
					</div>
					<div class="form-group">
						<label for="password">Password</label>
						<input required="" class="form-control" type="password" name="password" id="password" placeholder="">
					</div>
					<div class="form-group">
						<label for="password">Role</label>
						<select name="role" id="role" class="form-control" required="">
							<option value="">-- Pilih --</option>
							<option value="0">Admin</option>
							<option value="1">Karyawan</option>
						</select>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-primary btn-sm">SIMPAN</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@stop

resources/views/admin/users/edit.blade.php
@extends('layouts.backend.app',[
	'title' => 'Edit Users',
	'contentTitle' => 'Edit Users',
])
@section('content')
<div class="row">
	<div class="col">
		<div class="card">
			<div class="card-header">
				<a href="{{ route('admin.users.index') }}" class="btn btn-success btn-sm">Kembali</a>
			</div>
			<div class="card-body">
				<form method="POST" action="{{ route('admin.users.update',$user->id) }}">
					@csrf
					@method('PATCH')
					<div class="form-group">
						<label for="name">Full Name</label>
						<input value="{{ $user->name }}" required="" class="form-control" type="" name="name" id="name" placeholder="">
					</div>
					<div class="form-group">
						<label for="email">Email</label>
						<input value="{{ $user->email }}" required="" class="form-control" type="" name="email" id="email" placeholder="">
					</div>
					<div class="form-group">
						<label for="username">Username</label>
						<input value="{{ $user->username }}" required="" class="form-control" type="" name="username" id="username" placeholder="">
					</div>
					<div class="form-group">
						<label for="role">Role</label>
						<select name="role" id="role" class="form-control" required="">
							<option value="0" {{ ($user->role == 0)?'selected':'' }}>Admin</option>
							<option value="1" {{ ($user->role == 1)?'selected':'' }}>Pengelola</option>
						</select>
					</div>
					<div class="form-group">
						<label for="password">Password</label>
						<input value="{{ $user->password }}" type="hidden" name="old_password">
						<input class="form-control" type="password" name="password" id="password" placeholder="">
						<small class="text-secondary">Kosongkan kolom password jika tidak ingin mengubah password</small>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-primary btn-sm">UPDATE</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@stop

resources/views/admin/users/index.blade.php
@extends('layouts.backend.app',[
	'title' => 'Users',
	'contentTitle' => 'Users',
])
@push('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
@endpush
@section('content')
<x-alert></x-alert>
<div class="row">
	<div class="col">
		<div class="card">
			<div class="card-header">
				<a href="{{ route('admin.users.create') }}" class="btn btn-primary btn-sm">+ Tambah User</a>
			</div>
			<div class="card-body table-responsive">
				<table id="dataTable1" class="table table-bordered table-hover">
				<thead>
				<tr>
				  <th>No</th>
				  <th>Name</th>
				  <th>Email</th>
				  <th>Role</th>
				  <th>Action</th>
				</tr>
				</thead>
				<tbody>
				@php 
					$no=1;
				@endphp

				@foreach($users as $user)
				<tr>
				  <td>{{ $no++ }}</td>
				  <td>{{ $user->name }}</td>
				  <td>{{ $user->email }}</td>
				  <td>
					  @if ($user->role == 0)
					  Admin
					  @elseif ($user->role == 1)
					  Pengelola
					  @elseif ($user->role == 2)
					  Supervisor
					  @elseif ($user->role == 3)
					  Teknisi
				  	  @endif
				  </td>
				  <td>
				  	<div class="row ml-2">
				  		<a href="{{ route('admin.users.edit',$user->id) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit fa-fw"></i></a>
				  		<form method="POST" action="{{ route('admin.users.destroy',$user->id) }}">
				  			@csrf
				  			@method('DELETE')
				  			<button onclick="return confirm('Yakin hapus ?')" type="submit" class="btn btn-danger btn-sm ml-2"><i class="fas fa-trash fa-fw"></i></button>
				  		</form>
				  	</div>
				  </td>
				</tr>
				@endforeach
				</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@stop
@push('js')
<!-- DataTables -->
<script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/datatables/jquery.dataTables.js"></script>
<script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script>
  $(function () {
    $("#dataTable1").DataTable();
    $('#dataTable2').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": true,
    });
  });
</script>
@endpush