routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//Admin Namespace
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\ChangePasswordController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\WorkOrderAcController;
use App\Http\Controllers\Admin\WorkOrderPompaController;

//Controllers Namespace
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\PengumumanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//login
Route::get('/', 'AuthController@showFormLogin')->name('login');
Route::get('login', 'AuthController@showFormLogin')->name('login');
Route::post('login', 'AuthController@login');

//registration
Route::get('registrasi', 'RegisController@index')->name('regis');
Route::post('regis/form', 'RegisController@regisForm')->name('regisForm');
// Route::post('login', 'RegisController@login');

//Home
Route::get('/',[HomeController::class,'index']);
Route::get('/home',[AdminController::class,'index'])->name('index');
Route::get('/about',[HomeController::class,'about'])->name('about');
Route::get('/contact',[HomeController::class,'contact'])->name('contact');

//Artikel
// Route::get('/artikel',[ArtikelController::class,'index'])->name('artikel');
// Route::get('/artikel/search',[ArtikelController::class,'search'])->name('artikel.search');

// Route::get('/artikel/{artikel:slug}',[ArtikelController::class,'show'])->name('artikel.show');

//Pengumuman
Route::get('/pengumuman',[PengumumanController::class,'index'])->name('pengumuman');
Route::get('/pengumuman/{pengumuman:slug}',[PengumumanController::class,'show'])->name('pengumuman.show');

//WorkOrderPompa
// Route::get('/pompa',[WorkOrderPompaController::class,'index'])->name('pompa');
// Route::get('/pompa/search',[WorkOrderPompaController::class,'search'])->name('pompa.search');
// Route::get('/pompa/{pompa:slug}',[WorkOrderP\ompaController::class,'show'])->name('pompa.show');

Route::get('/pdf/{id}', 'Admin\WorkOrderAcController@pdf')->name('cetakPDF');
Route::get('/pompa/{id}', 'Admin\WorkOrderPompaController@pdf')->name('cetakPDFPompa');
Route::get('/alarm/{id}', 'Admin\WorkOrderFireAlarmController@pdf')->name('cetakPDFFireAlarm');

//Admin
Route::group(['namespace' => 'Admin','prefix' => 'admin','middleware' => ['auth']],function(){
	Route::name('admin.')->group(function(){

		Route::get('/',[AdminController::class,'index'])->name('index');
		Route::get('/profile',[ProfileController::class,'index'])->name('profile.index');
		Route::get('/change-password',[ChangePasswordController::class,'index'])->name('change-password.index');

		//Resource Controller
		Route::resource('users','UsersController');
		// Route::resource('pengumuman','PengumumanController');
		// Route::resource('agenda','AgendaController');
		Route::resource('wo_ac','WorkOrderAcController');
		// Route::resource('pompa','WorkOrderPompaController');
		// Route::resource('fire_alarm','WorkOrderFireAlarmController');
		Route::resource('perusahaan','PerusahaanController');
		Route::resource('department','DepartmentController');
		Route::resource('karyawan','KaryawanController');
		// Route::resource('alat','PeralatanController');
		// Route::resource('kategori-artikel','KategoriArtikelController');
	});
});

app/Models/Perusahaan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Perusahaan extends Model
{
    use HasFactory;

    // protected $table = 'artikel';
    protected $table = 'company';

    protected $fillable = [
    	'id','name','address','created_at','updated_at'
    ];
}

app/Http/Controllers/Admin/PerusahaanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Perusahaan;

class PerusahaanController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function index()
   {
       $perusahaan = Perusahaan::all();
       return view('admin.perusahaan.index', compact('perusahaan'));
   }
   /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function create()
   {
       return view('admin.perusahaan.create');
   }

   /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
   public function store(Request $request)
   {
       Perusahaan::create([
           'name'    => $request->name,
           'address' => $request->address
       ]);

       return redirect()->route('admin.perusahaan.index')->with('success','Data berhasil ditambah');
   }

   /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function show(Perusahaan $perusahaan)
   {
       return view('admin.perusahaan.show',compact('perusahaan'));
   }

   /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function edit(Perusahaan $perusahaan)
   {   
       return view('admin.perusahaan.edit',compact('perusahaan'));
   }

   /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function update(Request $request, Perusahaan $perusahaan)
   {
       $perusahaan->update($request->all());
          
       return redirect()->route('admin.perusahaan.index')->with('success','Data berhasil diupdate');
   }

   /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function destroy(Perusahaan $perusahaan)
   {   
       $perusahaan->delete();
       return redirect()->route('admin.perusahaan.index')->with('success','Data berhasil dihapus');
   }
}

resources/views/admin/perusahaan/create.blade.php
@extends('layouts.backend.app',[
	'title' => 'Tambah Perusahaan',
	'contentTitle' => 'Tambah Perusahaan'
])

@push('css')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/summernote') }}/summernote-bs4.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/dropify') }}/dist/css/dropify.min.css">
@endpush

@section('content')

<div class="">    
    <div class="card">
        <div class="card-header">
            <a href="{{ route('admin.perusahaan.index') }}" class="btn btn-success btn-sm">Kembali</a>
        </div>
        <div class="card-body">
        <form method="POST" enctype="multipart/form-data" action="{{ route('admin.perusahaan.store') }}">
            @csrf
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="name">Nama Perusahaan</label>
                        <input type="text" name="name" id="name" class="form-control" required>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="address">Alamat</label>
                        <input type="text" name="address" id="address" class="form-control" required>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-sm">SIMPAN</button>
            </div>
        </form>
    </div>
</div>

@stop

resources/views/admin/perusahaan/edit.blade.php
@extends('layouts.backend.app',[
	'title' => 'Edit Perusahaan',
	'contentTitle' => 'Edit Perusahaan'
])

@push('css')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/summernote') }}/summernote-bs4.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/dropify') }}/dist/css/dropify.min.css">
@endpush

@section('content')

<div class="">    
    <div class="card">
        <div class="card-header">
            <a href="{{ route('admin.perusahaan.index') }}" class="btn btn-success btn-sm">Kembali</a>
        </div>
        <div class="card-body">
        <form method="POST" enctype="multipart/form-data" action="{{ route('admin.perusahaan.update',$perusahaan->id) }}">
            @csrf
            @method('PATCH')
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="name">Nama Perusahaan</label>
                        <input value="{{ $perusahaan->name }}" type="text" name="name" id="name" class="form-control" required>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="address">Alamat</label>
                        <input value="{{ $perusahaan->address }}" type="text" name="address" id="address" class="form-control" required>
                    </div>
                </div>
            </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">UPDATE</button>
        </div>
        </form>
    </div>
</div>

@stop

@push('js')
{{-- <script type="text/javascript" src="{{ asset('plugins/summernote') }}/summernote-bs4.min.js"></script>
<script type="text/javascript" src="{{ asset('plugins/dropify') }}/dist/js/dropify.min.js"></script>
<script type="text/javascript">
    $(".summernote").summernote({
        height:500,
        callbacks: {
        // callback for pasting text only (no formatting)
            onPaste: function (e) {
              var bufferText = ((e.originalEvent || e).clipboardData || window.clipboardData).getData('Text');
              e.preventDefault();
              bufferText = bufferText.replace(/\r?\n/g, '<br>');
              document.execCommand('insertHtml', false, bufferText);
            }
        }
    })

    $(".summernote").on("summernote.enter", function(we, e) {
        $(this).summernote("pasteHTML", "<br><br>");
        e.preventDefault();
    });

    $('.dropify').dropify({
        messages: {
            default: 'Drag atau Drop untuk memilih gambar',
            replace: 'Ganti',
            remove:  'Hapus',
            error:   'error'
        }
    });

    $('.title').keyup(function(){
        var title = $(this).val().toLowerCase().replace(/[&\/\\#^, +()$~%.'":*?<>{}]/g,'-');
        $('.slug').val(title);
    });
</script> --}}
@endpush

resources/views/admin/perusahaan/index.blade.php
@extends('layouts.backend.app',[
    'title' => 'Perusahaan',
    'contentTitle' => 'Perusahaan',
])
@push('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
@endpush
@section('content')
<x-alert></x-alert>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <a href="{{ route('admin.perusahaan.create') }}" class="btn btn-primary btn-sm">+ Tambah Perusahaan</a>
            </div>
            <div class="card-body table-responsive">
              <table id="dataTable1" class="table table-bordered table-hover">
              <thead>
              <tr>
                <th>No</th>
                <th>Perusahaan</th>
                <th>Alamat</th>
                <th>Aksi</th>
              </tr>
              </thead>
              <tbody>
              @php 
                $no=1;
              @endphp
      
              @foreach($perusahaan as $perusahaan)
              <tr>
                <td>{{ $no }}</td>
                <td>{{ $perusahaan->name }}</td>
                <td>{{ $perusahaan->address }}</td>
                {{-- <td>{{ $alat->lokasi }}</td> --}}
                {{-- <td>{{ $alat->lokasi }}</td> --}}
                {{-- <td>
                  @if ($alat->status == 0)
                    Aktif
                  @else
                    Tidak Aktif
                  @endif
                </td> --}}
                <td>
                  <div class="row ml-2">
                    <a href="{{ route('admin.perusahaan.edit',$perusahaan->id) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit fa-fw"></i></a>
                    <form method="POST" action="{{ route('admin.perusahaan.destroy',$perusahaan->id) }}">
                      @csrf
                      @method('DELETE')
                      <button onclick="return confirm('Yakin hapus ?')" type="submit" class="btn btn-danger btn-sm ml-2"><i class="fas fa-trash fa-fw"></i></button>
                    </form>
                  </div>
                </td>
              </tr>
              @endforeach
              </tbody>
              </table>
            </div>
            
        </div>
    </div>
</div>
@stop
@push('js')
<!-- DataTables -->
<script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/datatables/jquery.dataTables.js"></script>
<script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script>
  $(function () {
    $("#dataTable1").DataTable();
  });
</script>
@endpush